In [18]:
import vincent
import pandas as pd
vincent.core.initialize_notebook()
pd.set_option("display.max_columns", None)

# Importing CSV DaTa

In [19]:
columns = ["Rk","G","Date","Age","Tm","Home/Away","Opp","Win/Lose","GS","MP","FG","FGA","FG%","3P","3PA","3P%",
           "FT","FTA","FT%","ORB","DRB","TRB","AST","STL","BLK","TOV","PF","PTS","GmSc","+/-"]

data = pd.read_csv("kevin.csv", names=columns)
data.head(10)

,Rk,G,Date,Age,Tm,Home/Away,Opp,Win/Lose,GS,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-
0,Rk,G,Date,Age,Tm,NaN,Opp,NaN,GS,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-
1,1,1,2012-11-01,24-033,OKC,@,SAS,L (-2),1,40:39,9,18,.500,1,2,.500,4,5,.800,2,12,14,5,2,0,4,1,23,19.7,+2
2,2,2,2012-11-02,24-034,OKC,NaN,POR,W (+14),1,42:41,7,14,.500,1,3,.333,8,12,.667,2,15,17,7,0,2,6,1,23,20.2,+13
3,3,3,2012-11-04,24-036,OKC,NaN,ATL,L (-9),1,42:05,7,17,.412,1,4,.250,7,8,.875,1,11,12,8,3,2,6,3,22,19.3,-8
4,4,4,2012-11-06,24-038,OKC,NaN,TOR,W (+20),1,29:09,4,11,.364,1,4,.250,6,6,1.000,0,6,6,3,2,0,4,3,15,9.6,+23
5,5,5,2012-11-08,24-040,OKC,@,CHI,W (+6),1,38:23,11,19,.579,0,2,.000,2,2,1.000,1,3,4,1,3,3,6,1,24,16.1,-3
6,6,6,2012-11-09,24-041,OKC,NaN,DET,W (+11),1,38:00,9,16,.563,2,2,1.000,5,5,1.000,1,12,13,2,1,0,3,1,25,20.7,+7
7,7,7,2012-11-11,24-043,OKC,NaN,CLE,W (+15),1,35:46,9,16,.563,1,2,.500,7,8,.875,0,8,8,2,0,1,2,1,26,20.1,+16
8,8,8,2012-11-12,24-044,OKC,@,DET,W (+2),1,43:49,8,22,.364,0,2,.000,10,10,1.000,0,9,9,3,0,4,2,1,26,19.0,+8
9,9,9,2012-11-14,24-046,OKC,NaN,MEM,L (-10),1,44:05,12,21,.571,1,1,1.000,9,9,1.000,0,10,10,5,3,2,5,1,34,29.6,-5

# Deleting Columns

In [20]:
del data["Rk"]
del data["Home/Away"]
del data["Tm"]
del data["Opp"]
del data["GS"]
del data["Win/Lose"]

In [17]:
data.head()

,G,Date,Age,Win/Lose,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-
0,G,Date,Age,NaN,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-
1,1,2012-11-01,24-033,L (-2),40:39,9,18,.500,1,2,.500,4,5,.800,2,12,14,5,2,0,4,1,23,19.7,+2
2,2,2012-11-02,24-034,W (+14),42:41,7,14,.500,1,3,.333,8,12,.667,2,15,17,7,0,2,6,1,23,20.2,+13
3,3,2012-11-04,24-036,L (-9),42:05,7,17,.412,1,4,.250,7,8,.875,1,11,12,8,3,2,6,3,22,19.3,-8
4,4,2012-11-06,24-038,W (+20),29:09,4,11,.364,1,4,.250,6,6,1.000,0,6,6,3,2,0,4,3,15,9.6,+23

# Field Goals Madr / Field Goals Attemped Per Minute

In [21]:
data[["MP", "FG", "FGA"]].dtypes

MP     object
FG     object
FGA    object
dtype: object